package com.toleey.smartorderingsystem.pojo;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.birthday
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.avator
     *
     * @mbggenerated
     */
    private String avator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.poiints
     *
     * @mbggenerated
     */
    private String poiints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.discount
     *
     * @mbggenerated
     */
    private String discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.debit
     *
     * @mbggenerated
     */
    private String debit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.address
     *
     * @mbggenerated
     */
    private Integer address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sos_user.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sos_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.id
     *
     * @return the value of sos_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.id
     *
     * @param id the value for sos_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.name
     *
     * @return the value of sos_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.name
     *
     * @param name the value for sos_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.gender
     *
     * @return the value of sos_user.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.gender
     *
     * @param gender the value for sos_user.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.phone
     *
     * @return the value of sos_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.phone
     *
     * @param phone the value for sos_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.birthday
     *
     * @return the value of sos_user.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.birthday
     *
     * @param birthday the value for sos_user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.avator
     *
     * @return the value of sos_user.avator
     *
     * @mbggenerated
     */
    public String getAvator() {
        return avator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.avator
     *
     * @param avator the value for sos_user.avator
     *
     * @mbggenerated
     */
    public void setAvator(String avator) {
        this.avator = avator == null ? null : avator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.poiints
     *
     * @return the value of sos_user.poiints
     *
     * @mbggenerated
     */
    public String getPoiints() {
        return poiints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.poiints
     *
     * @param poiints the value for sos_user.poiints
     *
     * @mbggenerated
     */
    public void setPoiints(String poiints) {
        this.poiints = poiints == null ? null : poiints.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.level
     *
     * @return the value of sos_user.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.level
     *
     * @param level the value for sos_user.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.discount
     *
     * @return the value of sos_user.discount
     *
     * @mbggenerated
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.discount
     *
     * @param discount the value for sos_user.discount
     *
     * @mbggenerated
     */
    public void setDiscount(String discount) {
        this.discount = discount == null ? null : discount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.debit
     *
     * @return the value of sos_user.debit
     *
     * @mbggenerated
     */
    public String getDebit() {
        return debit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.debit
     *
     * @param debit the value for sos_user.debit
     *
     * @mbggenerated
     */
    public void setDebit(String debit) {
        this.debit = debit == null ? null : debit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.address
     *
     * @return the value of sos_user.address
     *
     * @mbggenerated
     */
    public Integer getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.address
     *
     * @param address the value for sos_user.address
     *
     * @mbggenerated
     */
    public void setAddress(Integer address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sos_user.order
     *
     * @return the value of sos_user.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sos_user.order
     *
     * @param order the value for sos_user.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", phone=").append(phone);
        sb.append(", birthday=").append(birthday);
        sb.append(", avator=").append(avator);
        sb.append(", poiints=").append(poiints);
        sb.append(", level=").append(level);
        sb.append(", discount=").append(discount);
        sb.append(", debit=").append(debit);
        sb.append(", address=").append(address);
        sb.append(", order=").append(order);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}