package com.toleey.smartorderingsystem.dao;

import com.toleey.smartorderingsystem.pojo.Address;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_address
     *
     * @mbggenerated
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_address
     *
     * @mbggenerated
     */
    int insertSelective(Address record);
}