package com.toleey.smartorderingsystem.dao;

import com.toleey.smartorderingsystem.pojo.Carousel;

import java.util.List;

public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_carousel
     *
     * @mbggenerated
     */
    int insert(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_carousel
     *
     * @mbggenerated
     */
    int insertSelective(Carousel record);

    //查询全部的轮播图
    List<Carousel> getAlllCarousels();
}