package com.toleey.smartorderingsystem.dao;

import com.toleey.smartorderingsystem.pojo.Discount;

public interface DiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_discount
     *
     * @mbggenerated
     */
    int insert(Discount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_discount
     *
     * @mbggenerated
     */
    int insertSelective(Discount record);
}