package com.toleey.smartorderingsystem.dao;

import com.toleey.smartorderingsystem.pojo.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_order
     *
     * @mbggenerated
     */
    int insertSelective(Order record);
}