package com.toleey.smartorderingsystem.dao;

import com.toleey.smartorderingsystem.pojo.Item;
import com.toleey.smartorderingsystem.pojo.Order;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_order
     *
     * @mbggenerated
     */
    int insertSelective(Order record);

    public Integer submitItems(List<Item> itemList);

    public Integer submitAnOrder(Order order);

    //查询取餐码是否重复了
    public Integer selectFetchMealCode(Integer fetchMealCode);

    //查询全部订单
    public List<Order> getAllOrders();

}