package com.toleey.smartorderingsystem.dao;

import com.toleey.smartorderingsystem.pojo.Points;

public interface PointsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_points
     *
     * @mbggenerated
     */
    int insert(Points record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_points
     *
     * @mbggenerated
     */
    int insertSelective(Points record);
}