package com.toleey.smartorderingsystem.dao;

import com.toleey.smartorderingsystem.pojo.Redeem;

public interface RedeemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_redeem
     *
     * @mbggenerated
     */
    int insert(Redeem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_redeem
     *
     * @mbggenerated
     */
    int insertSelective(Redeem record);
}