package com.toleey.smartorderingsystem.dao;

import com.toleey.smartorderingsystem.pojo.Store;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_store
     *
     * @mbggenerated
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_store
     *
     * @mbggenerated
     */
    int insertSelective(Store record);
}