package com.toleey.smartorderingsystem.dao;

import com.toleey.smartorderingsystem.pojo.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sos_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    //获取全部用户信息
    public List<User> findAllUsers();

    //更新用户信息

    //临时换头像应付用
    public String provideAvatorSrc();
    public Integer updateAvatorSrc(String src);
}